services:
  dedplay-belge-seslendirme:
    build: .
    container_name: dedplay-belge-seslendirme
    restart: unless-stopped
    ports:
      - "7860:8000"
    volumes:
      - /var/lib/casaos_data/AppData/dedplay-belge-seslendirme/books:/app/books
      - /var/lib/casaos_data/AppData/dedplay-belge-seslendirme/output:/output
      - /root/.local/share/tts:/root/.local/share/tts
    environment:
      - TZ=Europe/Amsterdam
