services:
  dedplay-belge-seslendirme:
    build:
      context: https://github.com/berzahbey/dedplay-belge-seslendirme.git
    container_name: dedplay-belge-seslendirme
    restart: unless-stopped
    ports:
      - "7860:8000"
    volumes:
      - /DATA/AppData/dedplay-belge-seslendirme/books:/app/books
      - /DATA/AppData/dedplay-belge-seslendirme/output:/output
      - /DATA/AppData/dedplay-belge-seslendirme/tts_cache:/root/.local/share/tts
    environment:
      - TZ=Europe/Amsterdam
      - USE_GPU=true
    devices:
      - /dev/dri:/dev/dri
    privileged: true
